# Generated by Django 6.0.2 on 2026-03-04 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_alter_doctor_options_alter_doctor_room_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('in_progress', 'Qabulda'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='waiting', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queue_number'],
                'unique_together': {('patient', 'doctor', 'date')},
            },
        ),
    ]
