# Generated by Django 6.0.2 on 2026-03-04 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shifoxona nomi')),
                ('description', models.TextField(verbose_name="Batafsil ma'lumot")),
                ('address', models.TextField(verbose_name='Manzil')),
                ('estabished_data', models.DateField(verbose_name='Tashkil topgan sana')),
                ('image', models.ImageField(upload_to='hospitals/', verbose_name='Rasmi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name="Qo'llab-quvvatlash emaili")),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram link')),
                ('departments', models.ManyToManyField(related_name='hospitals', to='department.department', verbose_name="Mavjud bo'limlar")),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='region.region', verbose_name='Viloyatlar')),
            ],
        ),
    ]
