# Generated by Django 6.0.2 on 2026-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Shifoxona', 'verbose_name_plural': 'Shifoxonalar'},
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik (Latitude)'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik (Longitude)'),
        ),
    ]
