# Generated by Django 6.0.2 on 2026-03-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('hospital', '0002_alter_hospital_options_hospital_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=150, verbose_name='Mutaxasisligi')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Ish tajribasi (yil)')),
                ('room_number', models.IntegerField(verbose_name='Xona raqami')),
                ('work_hours', models.CharField(default='8:00-18:00', max_length=100, verbose_name='Ish vaqti')),
                ('is_aviable', models.BooleanField(default=True, verbose_name='Qabulga tayyor (active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='department.department', verbose_name="Bo'lim")),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.hospital', verbose_name='Shifoxona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Shifokorlar',
            },
        ),
    ]
