# Generated by Django 6.0.2 on 2026-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='room_number',
            field=models.PositiveIntegerField(verbose_name='Xona raqami'),
        ),
    ]
